In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('dataset_train.csv')

In [4]:
df.head()

,timestamp,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,...,Towers,MPG,LPS,Pressure_switch,Oil_level,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality
0,2022-01-01 06:00:00,-0.012,9.758,9.760,-0.028,1.576,63.350,19.049625,3.9550,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
1,2022-01-01 06:00:01,-0.012,9.760,9.760,-0.028,1.578,63.250,19.049625,4.0275,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
2,2022-01-01 06:00:02,-0.010,9.760,9.760,-0.028,1.578,63.325,19.040281,3.9450,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
3,2022-01-01 06:00:03,-0.012,9.756,9.756,-0.030,1.576,63.200,19.040281,3.9300,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1
4,2022-01-01 06:00:04,-0.012,9.756,9.756,-0.030,1.578,63.150,19.049625,3.9950,1,...,1,1,0,0,0,0,-8.65934,41.2124,0,1

TP2- Pressure on the compressor (bar).<br>
TP3- Pressure generated at the pneumatic panel (bar).<br>
H1- Valve that is activated when the pressure read by the pressure switch of the command is above the operating pressure of 10.2bar (bar).<br>
DV_pressure- Pressure exerted due to pressure drop generated when air dryers towers discharge the water. When it is equal to zero, the compressor is working under load (bar).<br>
Reservoirs- Pressure inside the air tanks installed on the trains (bar).<br>
Oil_Temperature- Temperature of the oil present on the compressor (°C).<br>
Flowmeter- Airfow was measured on the pneumatic control panel (m3/h).<br>
Motor_Current- Motor’s current, which should present the following values: (i) close to 0A when the compressor turns of; (ii) close to 4A when the compressor is working ofoaded; and (iii) close to 7A when the compressor is operating under load (A);

In [6]:
df.shape

(10773588, 21)

In [7]:
df.columns

Index(['timestamp', 'TP2', 'TP3', 'H1', 'DV_pressure', 'Reservoirs',
       'Oil_temperature', 'Flowmeter', 'Motor_current', 'COMP', 'DV_eletric',
       'Towers', 'MPG', 'LPS', 'Pressure_switch', 'Oil_level',
       'Caudal_impulses', 'gpsLong', 'gpsLat', 'gpsSpeed', 'gpsQuality'],
      dtype='object')

In [8]:
df.dtypes

timestamp           object
TP2                float64
TP3                float64
H1                 float64
DV_pressure        float64
Reservoirs         float64
Oil_temperature    float64
Flowmeter          float64
Motor_current      float64
COMP                 int64
DV_eletric           int64
Towers               int64
MPG                  int64
LPS                  int64
Pressure_switch      int64
Oil_level            int64
Caudal_impulses      int64
gpsLong            float64
gpsLat             float64
gpsSpeed             int64
gpsQuality           int64
dtype: object

In [9]:
# convert the time column to a datetime object
df['timestamp'] = pd.to_datetime(df['timestamp'])

# extract the month, day, hour, minute, and second into separate columns
df['Month'] = df['timestamp'].dt.strftime('%m')
df['Day'] = df['timestamp'].dt.strftime('%d')
df['Hour'] = df['timestamp'].dt.strftime('%H')
df['Minute'] = df['timestamp'].dt.strftime('%M')
df['Second'] = df['timestamp'].dt.strftime('%S')

In [10]:
df.dtypes

timestamp          datetime64[ns]
TP2                       float64
TP3                       float64
H1                        float64
DV_pressure               float64
Reservoirs                float64
Oil_temperature           float64
Flowmeter                 float64
Motor_current             float64
COMP                        int64
DV_eletric                  int64
Towers                      int64
MPG                         int64
LPS                         int64
Pressure_switch             int64
Oil_level                   int64
Caudal_impulses             int64
gpsLong                   float64
gpsLat                    float64
gpsSpeed                    int64
gpsQuality                  int64
Month                      object
Day                        object
Hour                       object
Minute                     object
Second                     object
dtype: object

In [12]:
df['Month'] = df['Month'].astype(float)
df['Day'] = df['Day'].astype(float)
df['Hour'] = df['Hour'].astype(float)
df['Minute'] = df['Minute'].astype(float)
df['Second'] = df['Second'].astype(float)

In [13]:
df = df.drop('timestamp', axis=1)

In [15]:
df.dtypes

TP2                float64
TP3                float64
H1                 float64
DV_pressure        float64
Reservoirs         float64
Oil_temperature    float64
Flowmeter          float64
Motor_current      float64
COMP                 int64
DV_eletric           int64
Towers               int64
MPG                  int64
LPS                  int64
Pressure_switch      int64
Oil_level            int64
Caudal_impulses      int64
gpsLong            float64
gpsLat             float64
gpsSpeed             int64
gpsQuality           int64
Month              float64
Day                float64
Hour               float64
Minute             float64
Second             float64
dtype: object

In [16]:
df.shape

(10773588, 25)

In [17]:
df.isnull().sum()

TP2                0
TP3                0
H1                 0
DV_pressure        0
Reservoirs         0
Oil_temperature    0
Flowmeter          0
Motor_current      0
COMP               0
DV_eletric         0
Towers             0
MPG                0
LPS                0
Pressure_switch    0
Oil_level          0
Caudal_impulses    0
gpsLong            0
gpsLat             0
gpsSpeed           0
gpsQuality         0
Month              0
Day                0
Hour               0
Minute             0
Second             0
dtype: int64

In [18]:
df.nunique()

TP2                 5440
TP3                 5173
H1                  5198
DV_pressure         3712
Reservoirs           317
Oil_temperature     3165
Flowmeter           1911
Motor_current       3196
COMP                   2
DV_eletric             2
Towers                 2
MPG                    2
LPS                    2
Pressure_switch        1
Oil_level              2
Caudal_impulses        2
gpsLong            13187
gpsLat              1567
gpsSpeed             147
gpsQuality             2
Month                  6
Day                   31
Hour                  21
Minute                60
Second                60
dtype: int64

In [19]:
unique_values = df['Hour'].unique()

In [20]:
unique_values

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19., 20., 21., 22., 23.,  0.,  1.,  2.])

at hours 3,4,5 we assume metro doesnt function

In [21]:
df.describe()

,TP2,TP3,H1,DV_pressure,Reservoirs,Oil_temperature,Flowmeter,Motor_current,COMP,DV_eletric,...,Caudal_impulses,gpsLong,gpsLat,gpsSpeed,gpsQuality,Month,Day,Hour,Minute,Second
count,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,...,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07,1.077359e+07
mean,1.152184e+00,8.974608e+00,7.751421e+00,-2.454095e-02,1.565051e+00,6.730720e+01,2.039515e+01,2.383179e+00,8.698926e-01,1.301137e-01,...,1.488919e-03,-4.384534e+00,2.091144e+01,4.913657e+00,5.076832e-01,3.046809e+00,1.556455e+01,1.312284e+01,2.949906e+01,2.949958e+01
std,3.075296e+00,7.006960e-01,3.051447e+00,1.486569e-01,9.016339e-02,5.383852e+00,3.743607e+00,2.193381e+00,3.364215e-01,3.364285e-01,...,3.855778e-02,4.317794e+00,2.059254e+01,1.151822e+01,4.999410e-01,1.461337e+00,8.814848e+00,6.458008e+00,1.731536e+01,1.731828e+01
min,-3.000000e-02,6.000000e-03,-3.400000e-02,-3.800000e-02,1.350000e+00,1.387500e+01,1.883472e+01,-1.250000e-02,0.000000e+00,0.000000e+00,...,0.000000e+00,-9.130040e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,-8.000000e-03,8.484000e+00,8.232000e+00,-3.200000e-02,1.470000e+00,6.367500e+01,1.901225e+01,2.500000e-03,1.000000e+00,0.000000e+00,...,0.000000e+00,-8.658910e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,8.000000e+00,9.000000e+00,1.500000e+01,1.400000e+01
50%,-8.000000e-03,8.984000e+00,8.746000e+00,-2.800000e-02,1.590000e+00,6.832500e+01,1.904028e+01,3.705000e+00,1.000000e+00,0.000000e+00,...,0.000000e+00,-8.542650e+00,4.115190e+01,0.000000e+00,1.000000e+00,3.000000e+00,1.600000e+01,1.400000e+01,2.900000e+01,2.900000e+01
75%,-6.000000e-03,9.492000e+00,9.290000e+00,-2.600000e-02,1.638000e+00,7.107500e+01,1.925519e+01,3.837500e+00,1.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,4.118820e+01,0.000000e+00,1.000000e+00,4.000000e+00,2.300000e+01,1.900000e+01,4.400000e+01,4.400000e+01
max,1.087600e+01,1.040800e+01,1.041400e+01,8.326000e+00,2.054000e+00,9.790000e+01,4.307241e+01,9.685000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,0.000000e+00,4.194900e+01,3.230000e+02,1.000000e+00,6.000000e+00,3.100000e+01,2.300000e+01,5.900000e+01,5.900000e+01

In [ ]:
df.plot.scatter(x='TP2', y='LPS')
df.plot.scatter(x='TP3', y='LPS')